Tech doc to Brand Brick
francineemilia/sdk-js pull request #1
Opened 2023-12-08 16:55 UTC by francineemilia

## 📝 Description

This PRs adds new documentation to the SDK JS 

## 📋 Changes

- [X] Adds new menu
- [X] Adds new doc

2023-12-08 19:59 UTC, icaldana commented on API/bricks/brand.md
> +mp.bricks().create("brand", "brandBrick_container", {});
Já compensaria deixar esse exemplo como 
```suggestion
mp.bricks().create("brand", "brandBrick_container");
```

O que acha?

2023-12-08 19:59 UTC, icaldana commented on API/bricks/brand.md
> +      useCustomFont: false,s
```suggestion
      useCustomFont: false,
```

2023-12-08 19:59 UTC, icaldana commented on API/bricks/brand.md
> +| `paymentMethods.excludedPaymentMethods`   | `string[]` | Defines which Payment Method will not be shown at Brand Brick. Example: card issuer, as `Visa`.
Faz diferença o `Visa` ser maiúsculo?

2023-12-08 19:59 UTC, icaldana commented on API/bricks/brand.md
> +| `text.fontWeight`                         | `string`   | Defines the font size to the texts at Brand Brick. The possible values are `semi-bold` or `regular`.
```suggestion
| `text.fontWeight`                         | `string`   | Defines the font weight to the texts at Brand Brick. The possible values are `semi-bold` or `regular`.                                                                                                                                                  | **OPTIONAL** |
```

2023-12-08 21:13 UTC, francineemilia commented on API/bricks/brand.md
> +| `paymentMethods.excludedPaymentMethods`   | `string[]` | Defines which Payment Method will not be shown at Brand Brick. Example: card issuer, as `Visa`.
@icaldana Faz. Eu acabei de corrigir explicando melhor.

2023-12-11 12:19 UTC, AleFossati requested changes

2023-12-11 12:19 UTC, AleFossati commented on API/bricks/brand.md
> +      border: false,
como tem outras propriedades de borda que só serão afetadas se a borda existir, acho mais interessante deixar como `true` aqui

2023-12-11 12:19 UTC, AleFossati commented on API/bricks/brand.md
> +| `text.useCustomFont`                      | `boolean`  | Defines if will be used a custom font or if it will adopt the standart font to Brand Brick. The possible values are `true` or `false`.
Para deixar super claro como o brick vai saber qual fonte usar caso seja `true`, acho que vale adicionar o seguinte ao final:

> If `true`, brand brick will inherit the font-family from the container

2023-12-11 12:19 UTC, AleFossati commented on API/bricks/brand.md
> +| `visual.borderColor`                      | `string`   | Defines the border color if it is be showned. The possible values are `light` or `dark`.
Achei a frase um pouco estranha e joguei no gepeto, essa foi a resposta:

> A frase contém um pequeno erro. A forma correta seria:
> "Defines the border color if it is to be shown."
> ou
> "Defines the border color if it is going to be shown."

Eu acho que podemos simplificar, deixando assim mesmo (vale também para as propriedades seguintes que estão escritas da mesma forma):

```suggestion
| `visual.borderColor`                      | `string`   | Defines the border color. The possible values are `light` or `dark`.                                                                                                                                                              | **OPTIONAL** |
```

2023-12-11 12:19 UTC, AleFossati commented on API/bricks/brand.md
> +| `visual.contentAlign`                     | `string`   | Defines the content alignement - text and images - inside de Brand Brick. The possible values are `left`, `center` or `right`.
```suggestion
| `visual.contentAlign`                     | `string`   | Defines the content alignment - text and images - inside de Brand Brick. The possible values are `left`, `center` or `right`.                                                                                                                        | **OPTIONAL** |
```

2023-12-11 12:24 UTC, AleFossati commented on API/bricks/brand.md
> +| `paymentMethods`                          | `object`   | Controls which information about payment methods and payment method types will apear on the Brand Brick - at the default render and modal. C
_Detalhe que peguei jogando todo o texto no google docs:_

```suggestion
| `paymentMethods`                          | `object`   | Controls which information about payment methods and payment method types will appear on the Brand Brick - at the default render and modal. Contains `excludedPaymentMethods`,`excludedPaymentTypes`,`maxInstallments` and `interestFreeInstallments`. | **OPTIONAL** |
```

2023-12-11 12:24 UTC, AleFossati commented on API/bricks/brand.md
> +| `paymentMethods.maxInstallments`          | `number`   | Defines which value will be shown as maximum installments accepted by the seller. If filled, the value start at `2` and the maximum allowed
_Detalhe que peguei jogando todo o texto no google docs:_

```suggestion
| `paymentMethods.maxInstallments`          | `number`   | Defines which value will be shown as maximum installments accepted by the seller. If filled, the value starts at `2` and the maximum allowed to show is `12`.                                                                                          | **OPTIONAL** |
```

2023-12-11 12:24 UTC, AleFossati commented on API/bricks/brand.md
> +| `text.useCustomFont`                      | `boolean`  | Defines if will be used a custom font or if it will adopt the standart font to Brand Brick. The possible values are `true` or `false`.
_Detalhe que peguei jogando todo o texto no google docs:_

```suggestion
| `text.useCustomFont`                      | `boolean`  | Defines if will be used a custom font or if it will adopt the standard font to Brand Brick. The possible values are `true` or `false`.                                                                                                                | **OPTIONAL** |
```

2023-12-11 12:24 UTC, AleFossati commented on API/bricks/brand.md
> +| `visual.hideMercadoPagoLogo`              | `boolean`  | Defines if the MercadoPago logos will be show at Brand Brick. The possible values are `true` or `false`.
_Detalhe que peguei jogando todo o texto no google docs:_

```suggestion
| `visual.hideMercadoPagoLogo`              | `boolean`  | Defines if the MercadoPago logos will be shown at Brand Brick. The possible values are `true` or `false`.                                                                                                                                              | **OPTIONAL** |
```

2023-12-11 14:08 UTC, meliguicarvalho commented on API/bricks/brand.md
> +      interestFreeInstallments: false,
Fran, acho que seria melhor passar configurações não padrão para esse exemplo, não?

2023-12-11 14:08 UTC, meliguicarvalho commented on API/bricks/brand.md
> +| `paymentMethods.excludedPaymentMethods`   | `string[]` | Defines which Payment Method will not be shown at Brand Brick. Example: card issuer, as `visa`. The payment method name needs to be lower ca
Esses tipos, `excludedPaymentMethods` e `excludedPaymentTypes`, acho que o ideal seria especificar os valores possiveis, isso esta tipado no Brick, e acho que vale a pena deixar explicito nessa doc

2023-12-11 14:08 UTC, meliguicarvalho commented on API/bricks/brand.md
> +| `text`                                    | `object`   | Controls which message will appear on the Brand Brick. Contains `valueProp`, `useCustomFont`, `textSize`, `fontWeight` and `textColor`.
acho que aqui ficaria mais claro definir como algo do tipo: `controls the text contents and text appearance on Brand Brick`

2023-12-11 14:11 UTC, AleFossati commented on API/bricks/brand.md
> +| `visual.borderRadius`                     | `string`   | Defines the border radius if it is be showned. The possible values are expressed in pixels in the format `Npx`
```suggestion
| `visual.borderRadius`                     | `string`   | Defines the border radius. The possible values are expressed in pixels in the format `Npx`                                                                                                                                         | **OPTIONAL** |
```

2023-12-11 14:11 UTC, AleFossati commented on API/bricks/brand.md
> +| `visual.borderWidth`                      | `string`   | Defines the border color if it is be showned. The possible values are `1px` or `2px`.
```suggestion
| `visual.borderWidth`                      | `string`   | Defines the border color. The possible values are `1px` or `2px`.                                                                                                                                                                  | **OPTIONAL** |
```

2023-12-11 14:43 UTC, AleFossati approved these changes

2023-12-11 18:47 UTC, meliguicarvalho approved these changes

2023-12-11 19:31 UTC, merged

2023-12-12 14:59 UTC, meliguicarvalho commented on API/bricks/brand.md
> +| `text.textSize`                           | `string`   | Defines the font size to the texts at Brand Brick. The possible values are `extra-small`, `small`, `medium` or `large`.
mudar para extra_small